[build]
  publish = "public"
  command = "npm run build"
  functions = "lambda"
[build.environment]
  YARN_VERSION = "1.9.4"
  YARN_FLAGS = "--no-ignore-optional"
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

    #  Multi-key header rules are expressed with multi-line strings
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''

    # The Basic-Auth header may not be available on all plans.
    Basic-Auth = "admin:password anotheruser:anotherpassword"