backend:
  name: git-gateway

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img
media_library:
  name: uploadcare
  config:
    publicKey: 7b969f8af066608712d4

logo_url: https://i.ibb.co/9HVyrzQ/android-chrome-144x144.png

collections:
  - name: 'project'
    label: 'Project'
    folder: 'src/pages/project'
    create: true
    slug: '{{client}}_{{title}}'
    editor:
      preview: false
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'project-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Meta Description', name: 'description', widget: 'text', hint: 'Project description for SEO and social-media sharing' }
      - { label: 'Meta Image', name: 'metaImage', widget: 'image', hint: 'Project image for SEO and social-media sharing' }
      - { label: 'Primary Color', name: 'primaryColor', widget: 'string', hint: 'Use HEX value from: https://www.google.com/search?q=color+picker', required: true }
      - { label: 'Secondary Color', name: 'secondaryColor', widget: 'string', hint: 'Use HEX value from: https://www.google.com/search?q=color+picker', required: false }
      - {
          label: 'Protected Project',
          name: 'protectedProject',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Featured Project',
          name: 'featured',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Featured Animation (JSON)',
          name: 'featuredJson',
          widget: file,
          media_library: {
            config: {
              accept: '.json'
            }
          }
        }
      - {
        label: "Featured Project Weight",
        hint: "'Lighter' projects 'float', to the top.",
        name: "featuredProjectSort",
        widget: "number",
        default: 1,
        valueType: "int",
        min: 1,
        max: 100,
        step: 1,
        required: false
      }
      - { label: 'Project Index SVG',
          name: 'indexSvg',
          widget: file,
          media_library: {
            config: {
              accept: '.svg'
            }
          }
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Client', name: 'client', widget: 'string' }
      - { label: 'Team', name: 'team', widget: 'list', required: false }
      - { label: 'Press', name: 'press', widget: 'list', required: false }
      - label: 'Modules'
        name: 'modules'
        widget: 'list'
        types:
          - label: 'Project Banner'
            name: 'projectBanner'
            widget: 'object'
            fields:
              - label: 'Project Banner Media'
                name: 'projectBannerMedia'
                widget: 'file'
              - label: 'Project Banner Media Thumbnail'
                name: 'projectBannerMediaThumbnail'
                widget: 'file'
                required: false
                hint: 'Image to display when video media is loading'
          - label: 'Header'
            name: 'header'
            widget: 'object'
            fields:
              - { label: 'Header Text', name: 'headerText', widget: 'string' }
          - label: 'Text Area'
            name: 'textArea'
            widget: 'object'
            fields:
              - label: 'Text Columns'
                name: 'textColumns'
                widget: 'list'
                fields:
                  - { label: 'Column', name: 'column', widget: 'markdown' }
          - label: 'Media Grid'
            name: 'mediaGrid'
            widget: 'object'
            fields:
              - label: 'Media'
                name: 'mediaGridMedia'
                widget: 'list'
                fields:
                  - { label: 'Media', name: 'mediaGridMediaFile', widget: file}
                  - { label: 'Caption', name: 'caption', widget: 'string', required: false }
                  - { label: 'Media Thumbnail', name: 'mediaGridMediaFileThumbnail', widget: file, required: false, hint: 'Image to display while video media loads, add this if the media file is a video.'}
              - label: 'Hide all captions'
                name: 'hideCaptions'
                widget: 'boolean'
                default: false
                required: false
                hint: 'Do not display captions.'
          - label: 'Large Media'
            name: 'largeMedia'
            widget: 'object'
            fields:
              - { label: 'Media', name: 'largeMediaFile', widget: 'file' }
              - { label: 'Caption', name: 'caption', widget: 'string', required: false}
              - {
                  label: 'Bleed',
                  name: 'bleed',
                  widget: 'boolean',
                  hint: 'Display media without margin or padding',
                  default: false,
                  required: false,
                }
              - { label: 'Media Thumbnail', name: 'largeMediaFileThumbnail', widget: file, required: false, hint: 'Image to display while video media loads, add this if the media file is a video.'}
          - label: 'Gallery'
            name: 'gallery'
            widget: 'object'
            fields:
              - label: 'Slides'
                name: 'slides'
                widget: 'list'
                types:
                  - label: 'Slide'
                    name: 'slideMedia'
                    widget: 'object'
                    fields:
                      - { label: 'Media', name: 'slideMediaFile', widget: 'file' }
                      - { label: 'Caption', name: 'caption', widget: 'string', required: false }
                      - { label: 'Media Thumbnail', name: 'slideMediaFileThumbnail', widget: file, required: false, hint: 'Image to display while video media loads, add this if the media file is a video.'}
          - label: 'Mobile Device'
            name: 'mobileDevice'
            widget: 'object'
            fields:
              - label: 'Mobile Device Media'
                name: 'mobileDeviceMedia'
                widget: 'file'
              - { label: 'Media Thumbnail', name: 'mobileDeviceMediaFileThumbnail', widget: file, required: false, hint: 'Image to display while video media loads, add this if the media file is a video.'}
          - label: 'Tablet Device'
            name: 'tabletDevice'
            widget: 'object'
            fields:
              - label: 'Tablet Device Media'
                name: 'tabletDeviceMedia'
                widget: 'file'
              - { label: 'Media Thumbnail', name: 'tabletDeviceMediaFileThumbnail', widget: file, required: false, hint: 'Image to display while video media loads, add this if the media file is a video.'}
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Studio Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'text' }
          - { label: 'Address', name: 'address', widget: 'string' }
          - { label: 'Phone', name: 'phone', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }
          - {
              label: 'Social',
              name: 'social',
              widget: 'list',
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'URL', name: 'url', widget: 'string' },
                ],
            }
      - file: 'src/pages/legal/index.md'
        label: 'Legal Page'
        name: 'legal'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'legal-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
      - file: 'src/pages/cookie/index.md'
        label: 'Cookie Page'
        name: 'cookie'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'cookie-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
      - file: 'src/pages/404/index.md'
        label: '404 Page'
        name: 'not-found-page'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'not-found-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
