backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img
media_library:
  name: uploadcare
  config:
    publicKey: 70d063a0b7e99e040bf8

collections:
  - name: 'project'
    label: 'Project'
    folder: 'src/pages/project'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'project-post',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Protected Post', name: 'protectedpost', widget: 'boolean' }
      - { label: 'Featured Post', name: 'featuredpost', widget: 'boolean' }
      - { label: 'Featured Image', name: 'featuredimage', widget: image }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - label: 'Modules'
        name: 'modules'
        widget: 'list'
        types:
          - label: 'Project Banner'
            name: 'projectBanner'
            widget: 'object'
            fields:
              - label: 'Project Banner Media'
                name: 'projectBannerMedia'
                widget: 'file'
                types:
                  - label: 'Banner Image'
                    name: 'bannerImage'
                    widget: 'object'
                    fields:
                      - { label: 'Image', name: 'image', widget: 'image' }
                  - label: 'Banner Video'
                    name: 'bannerVideo'
                    widget: 'object'
                    fields:
                      - {
                          label: 'Video URL',
                          name: 'videoURL',
                          widget: 'string',
                        }
                  - label: 'Banner File'
                    name: 'bannerFile'
                    widget: 'object'
                    fields:
                      - { label: 'File', name: 'file', widget: 'file' }
          - label: 'Header'
            name: 'header'
            widget: 'object'
            fields:
              - { label: 'Header Text', name: 'headerText', widget: 'string' }
          - label: 'Text Area'
            name: 'textArea'
            widget: 'object'
            fields:
              - label: 'Text Columns'
                name: 'textColumns'
                widget: 'list'
                fields:
                  - { label: 'Column', name: 'column', widget: 'markdown' }
          - label: 'Image Grid'
            name: 'imageGrid'
            widget: 'object'
            fields:
              - label: 'Images'
                name: 'images'
                widget: 'list'
                fields:
                  - { label: 'Image', name: image, widget: image }
          - label: 'Large Image'
            name: 'largeImage'
            widget: 'object'
            fields:
              - { label: 'Caption', name: 'caption', widget: 'string' }
              - { label: 'Image', name: 'image', widget: 'image' }
              - {
                  label: 'Bleed',
                  name: 'bleed',
                  widget: 'boolean',
                  hint: 'Display image without margin or pagging',
                }
          - label: 'Gallery'
            name: 'gallery'
            widget: 'object'
            fields:
              - label: 'Slides'
                name: 'slides'
                widget: 'list'
                types:
                  - label: 'Image Slide'
                    name: 'imageSlide'
                    widget: 'object'
                    fields:
                      - { label: 'Image', name: 'image', widget: 'image' }
                      - { label: 'Caption', name: 'caption', widget: 'string' }
                  - label: 'Video Slide'
                    name: 'videoSlide'
                    widget: 'object'
                    fields:
                      - {
                          label: 'Video URL',
                          name: 'videoURL',
                          widget: 'string',
                        }
                      - { label: 'Caption', name: 'caption', widget: 'string' }
                  - label: 'File Slide'
                    name: 'fileSlide'
                    widget: 'object'
                    fields:
                      - { label: 'File', name: 'file', widget: 'file' }
                      - { label: 'Caption', name: 'caption', widget: 'string' }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'src/pages/index.md'
        label: 'Studio Page'
        name: 'index'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'index-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Address', name: 'address', widget: 'string' }
          - { label: 'Phone', name: 'phone', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }
          - {
              label: 'Social',
              name: 'social',
              widget: 'list',
              fields:
                [
                  { label: 'Title', name: 'title', widget: 'string' },
                  { label: 'URL', name: 'url', widget: 'string' },
                ],
            }
      - file: 'src/pages/legal/index.md'
        label: 'Legal Page'
        name: 'legal'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'legal-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
      - file: 'src/pages/cookie/index.md'
        label: 'Cookie Page'
        name: 'cookie'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'cookie-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
      - file: 'src/pages/404/index.md'
        label: '404 Page'
        name: 'not-found-page'
        fields:
          - {
              label: 'Template Key',
              name: 'templateKey',
              widget: 'hidden',
              default: 'not-found-page',
            }
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Description', name: 'description', widget: 'markdown' }
