backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  
  - name: "project"
    label: "Project"
    folder: "src/pages/project"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: 
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Protected Post", name: "protectedpost", widget: "boolean"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Tags", name: "tags", widget: "list"}
      - label: "Modules"
        name: "modules"
        widget: "list"
        types:
          - label: "Project Banner"
            name: "projectBanner"
            widget: "object"
            fields: 
              - label: "Project Banner Media"
                name: "projectBannerMedia"
                widget: "file"
                types:
                  - label: "Banner Image"
                    name: "bannerImage"
                    widget: "object"
                    fields:
                      - { label: "Image", name: "image", widget: "image" }
                  - label: "Banner Video"
                    name: "bannerVideo"
                    widget: "object"
                    fields:
                      - { label: "Video URL", name: "videoURL", widget: "string" }
                  - label: "Banner File"
                    name: "bannerFile"
                    widget: "object"
                    fields:
                      - { label: "File", name: "file", widget: "file" }
          - label: "Header"
            name: "header"
            widget: "object"
            fields:
              - { label: "Header Text", name: "headerText", widget: "string" }
          - label: "Text Area"
            name: "textArea"
            widget: "object"
            fields:
              - label: "Text Columns"
                name: "textColumns"
                widget: "list"
                fields:
                  - { label: "Column", name: "column", widget: "markdown" }
          - label: "Image Grid"
            name: "imageGrid"
            widget: "object"
            fields:
              - label: "Images"
                name: "images"
                widget: "list"
                fields:
                  - { label: "Image", name: image, widget: image }
          - label: "Large Image"
            name: "largeImage"
            widget: "object"
            fields:
              - { label: "Caption", name: "caption", widget: "string" }
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Bleed", name: "bleed", widget: "boolean", hint: "Display image without margin or pagging" }
          - label: "Gallery"
            name: "gallery"
            widget: "object"
            fields:
              - label: "Slides"
                name: "slides"
                widget: "list"
                types:
                  - label: "Image Slide"
                    name: "imageSlide"
                    widget: "object"
                    fields:
                      - { label: "Image", name: "image", widget: "image" }
                      - { label: "Caption", name: "caption", widget: "string" }
                  - label: "Video Slide"
                    name: "videoSlide"
                    widget: "object"
                    fields:
                      - { label: "Video URL", name: "videoURL", widget: "string" }
                      - { label: "Caption", name: "caption", widget: "string" }
                  - label: "File Slide"
                    name: "fileSlide"
                    widget: "object"
                    fields:
                      - { label: "File", name: "file", widget: "file" }
                      - { label: "Caption", name: "caption", widget: "string" }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields: 
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Social", name: "social", widget: "list", fields: [{label: "Title", name: "title", widget: "string"}, {label: "URL", name: "url", widget: "string"}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
